using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace RgiSequenceFinder.TableGenerator
{
    class SourceGenerator
    {
        public static void Write(StreamWriter writer, GroupedEmojis emojis)
        {
            WriteHeader(writer);
            WriteKeycaps(writer, emojis.Keycaps);
            WriteRegionFlags(writer, emojis.RegionFlags);
            WriteTagFlags(writer, emojis.TagFlags);
            WriterOthers(writer, emojis.Others);
            WriteFooter(writer);
        }

        private static void WriteHeader(StreamWriter writer)
        {
            writer.Write(@"// <auto-generated>
// RgiSequenceFinder.TableGenerator
// </auto-generated>

namespace RgiSequenceFinder
{
    partial class RgiTable
    {
");
        }

        private static void WriteFooter(StreamWriter writer)
        {
            writer.Write(@"    }
}
");
        }

        private static void WriteKeycaps(StreamWriter writer, List<(Keycap key, int index)> keycaps)
        {
            writer.Write(@"        private static int FindKeycap(Keycap key) => key.Value switch
        {
");

            foreach (var (key, index) in keycaps)
            {
                writer.Write("            (byte)'");
                writer.Write((char)key.Value);
                writer.Write("' => ");
                writer.Write(index);
                writer.Write(@",
");
            }

            writer.Write(@"            _ => -1,
        };

");
        }

        private static void WriteRegionFlags(StreamWriter writer, List<(RegionalIndicator code, int index)> regionFlags)
        {
            writer.Write(@"        private static int FindRegion(RegionalIndicator region) => region.First switch
        {
");

            foreach (var g in regionFlags.GroupBy(x => x.code.First))
            {
                writer.Write("            (byte)'");
                writer.Write((char)g.Key);
                writer.Write(@"' => region.Second switch
            {
");

                foreach (var (ri, index) in g)
                {
                    writer.Write("                (byte)'");
                    writer.Write((char)ri.Second);
                    writer.Write("' => ");
                    writer.Write(index);
                    writer.Write(@",
");
                }

                writer.Write(@"                _ => -1,
            },
");
            }

            writer.Write(@"            _ => -1,
        };

");
        }

        private static void WriteTagFlags(StreamWriter writer, List<(Byte8 tag, int index)> tagFlags)
        {
            writer.Write(@"        private static int FindTag(Byte8 tags) => tags.LongValue switch
        {
");
            foreach (var (tags, index) in tagFlags)
            {
                writer.Write("            0x");
                writer.Write(tags.LongValue.ToString("X"));
                writer.Write("UL => ");
                writer.Write(index);
                writer.Write(@",
");
            }

            writer.Write(@"            _ => -1,
        };

");
        }

        private static void WriterOthers(StreamWriter writer, List<(string emoji, int index)> others)
        {
            // other 分、いったん Dictionary 実装する。
            // string → int で型が固定、容量も固定、キー検索に ReadOnlySpan<char> 受付可能な自作ハッシュテーブル(StringDictionary)は用意してある。
            //
            // 今のこの Dictionary 実装だと 80 KB くらいバイナリサイズが膨らむ。

#if false
/* いくつかもうちょっと絵文字の事前知識使ってもいいかも:

(UTF - 16 で) 1文字のものは char → short なハッシュテーブルも別に用意するとアロケーション減るかも。

- 1文字のシーケンスは 2000～3300 付近にしかない

(UTF-16 で) 2文字、3文字のシーケンスも実質1文字のテーブルにできるものあり。

- 2文字のシーケンス
    - 2文字目が FE0F(異体字セレクター16)なもの多数
      - \u00A9\uFE0F と \u00AE\uFE0F 以外は全部 2000～3300 付近
    - 1文字目が D83C～D83F(1F000 台の符号点の high surrogate)な物がほとんど
- 3文字のシーケンス
    - 1文字目が D83C～D83F、3文字目が FE0F なもの多数

それ以上の長さのものも、1文字目が D83C～D83F の率やっぱりだいぶ高め
*/
#endif

            writer.Write(@"        private static StringDictionary _otherTable = new()
        {
");

            foreach (var (s, index) in others)
            {
                writer.Write("            { \"");

                foreach (var c in s)
                {
                    writer.Write("\\u");
                    writer.Write(((int)c).ToString("X4"));
                }

                writer.Write("\", ");
                writer.Write(index);
                writer.Write(@" },
");
            }

            writer.Write(@"        };

        private static int FindOther(System.ReadOnlySpan<char> s) => _otherTable.TryGetValue(s, out var v) ? v : -1;
");
        }

#if false
// こういう実装も試してみたという形跡。
//
// ReadOnlySpan<char> 引数を付けつけできるように switch 化したもの。
// そんなに (a, b, c, ...) switch { ... } みたいなやつ、「1文字目が同じなら1つの if になる」みたいな最適化は掛かるけど、
// 代わりに goto が大量にあるコードになって、バイナリサイズは Dictionary<string, int> を持つ実装よりもでかくなった。
// 線形探索になりそうだし Dictionary 実装よりも遅そう。
//
// 素直に、TryGetValue(ReadOnlySpan<char>) ができる StringDictionary を書いた方がよさそう。

        private static void WriteOthers(StreamWriter writer, List<(string emoji, int index)> others)
        {
            writer.Write(@"        private static int FindOther(System.ReadOnlySpan<char> emoji) => emoji.Length switch
        {
");

            foreach (var g in others.GroupBy(x => x.emoji.Length).OrderBy(g => g.Key))
            {
                var length = g.Key;

                writer.Write("            ");
                writer.Write(length);
                writer.Write(" => ");

                for (int i = 0; i < length; i++)
                {
                    if (i == 0) writer.Write('(');
                    else writer.Write(", ");
                    writer.Write("emoji[");
                    writer.Write(i);
                    writer.Write("]");
                }

                writer.Write(@") switch
            {
");

                foreach (var (emoji, index) in g)
                {
                    writer.Write("                ");

                    for (int i = 0; i < length; i++)
                    {
                        if (i == 0) writer.Write('(');
                        else writer.Write(", ");
                        writer.Write("'\\u");
                        writer.Write(((int)emoji[i]).ToString("X4"));
                        writer.Write("'");
                    }

                    writer.Write(") => ");
                    writer.Write(index);
                    writer.Write(@",
");
                }

                writer.Write(@"                _ => -1,
            },
");
            }

            writer.Write(@"            _ => -1,
        };

");
        }
#endif
    }
}
