using System.IO;
using System.Linq;
using System.Text;

namespace EmojiData
{
    class SourceGenerator
    {
        public static void WriteLineTest(Rune[][] emojiSequenceList)
        {
            foreach (var seq in emojiSequenceList.Take(100))
            {
                var s = Encoder.ToString(seq);

                foreach (var c in s)
                {
                    System.Console.Write($"{(int)c:X4} ");
                }
                System.Console.WriteLine();
                System.Console.WriteLine(Encoder.ToEscapedString(seq));
            }
        }

        public static void WriteRgiEmojiSequenceList(Rune[][] emojiSequenceList, string path)
        {
            using var w = new StreamWriter(path, false, Encoding.UTF8);
            WriteRgiEmojiSequenceList(emojiSequenceList, w);
        }

        public static void WriteRgiEmojiSequenceList(Rune[][] emojiSequenceList, TextWriter writer)
        {
            writer.Write(@"// <auto-generated>
// EmojiData.SourceGenerator
// </auto-generated>

namespace RgiSequenceFinder
{
    partial class Data
    {
        public static readonly string[] RgiEmojiSequenceList = new[]
        {
");

            foreach (var seq in emojiSequenceList)
            {
                var s = Encoder.ToEscapedString(seq);
                writer.Write(@"            """);
                writer.Write(s);
                writer.Write(@""",
");
            }

            writer.Write(@"        };
    }
}
");
        }

        public static void WriteUnvariedRgiEmojiSequenceList((Rune[] runes, int index, int variationType)[] emojiSequenceList, string path)
        {
            using var w = new StreamWriter(path, false, Encoding.UTF8);
            WriteUnvariedRgiEmojiSequenceList(emojiSequenceList, w);
        }

        public static void WriteUnvariedRgiEmojiSequenceList((Rune[] runes, int index, int variationType)[] emojiSequenceList, TextWriter writer)
        {
            writer.Write(@"// <auto-generated>
// EmojiData.SourceGenerator
// </auto-generated>

namespace RgiSequenceFinder
{
    partial class Data
    {
        public static readonly (string emoji, ushort index, byte variationType)[] UnvariedRgiEmojiSequenceList = new (string, ushort, byte)[]
        {
");

            foreach (var seq in emojiSequenceList)
            {
                var s = Encoder.ToEscapedString(seq.runes);
                writer.Write(@"            (""");
                writer.Write(s);
                writer.Write("\", ");
                writer.Write(seq.index);
                writer.Write(", ");
                writer.Write(seq.variationType);
                writer.Write(@"),
");
            }

            writer.Write(@"        };
    }
}
");
        }
    }
}
